"""add firm to records

Revision ID: 07a2d02f6e8e
Revises: 5923d62faa6f
Create Date: 2026-05-04 14:31:52.056814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a2d02f6e8e'
down_revision: Union[str, Sequence[str], None] = '5923d62faa6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('firm', sa.String(), nullable=False))
    op.alter_column('records', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('records', 'firm')
    # ### end Alembic commands ###
