export const companiesData = [
  {
    id: 1,
    name: "Valley Education",
    phone: "+40 758 177 097",
    email: "finance@valleyedu.org",
    address: "Str. Visinului, Bacau",
    contactPerson: { name: "Dr. Sarah Mitchell", email: "sarah.mitchell@valleyedu.org" },
    observations: [],
  },
  {
    id: 2,
    name: "Acme Corporation",
    phone: "+40 722 100 200",
    email: "info@acme.com",
    address: "Bulevardul Eroilor, Cluj-Napoca",
    contactPerson: { name: "John Doe", email: "j.doe@acme.com" },
    observations: [],
  },
  {
    id: 3,
    name: "TechStart Inc.",
    phone: "+40 744 333 444",
    email: "contact@techstart.io",
    address: "Str. Memorandumului, Cluj-Napoca",
    contactPerson: { name: "Alice Vance", email: "alice@techstart.io" },
    observations: [],
  },
  {
    id: 4,
    name: "Global Logistics",
    phone: "+40 733 555 666",
    email: "logistics@global.ro",
    address: "Calea Turzii, Cluj-Napoca",
    contactPerson: { name: "Mark Stevens", email: "m.stevens@global.ro" },
    observations: [],
  },
  {
    id: 5,
    name: "Riverside Medical",
    phone: "+40 788 111 222",
    email: "office@riverside.med",
    address: "Str. Clinicilor, Cluj-Napoca",
    contactPerson: { name: "Elena Popescu", email: "e.popescu@riverside.med" },
    observations: [],
  },
  {
    id: 6,
    name: "Downtown Retail",
    phone: "+40 755 999 000",
    email: "sales@downtown.ro",
    address: "Str. Regele Ferdinand, Cluj-Napoca",
    contactPerson: { name: "George Marin", email: "g.marin@downtown.ro" },
    observations: [],
  },
  {
    id: 7,
    name: "Mountain Coffee",
    phone: "+40 741 222 333",
    email: "hello@mtncoffee.com",
    address: "Str. Avram Iancu, Brasov",
    contactPerson: { name: "Ana Maria", email: "ana@mtncoffee.com" },
    observations: [],
  },
  {
    id: 8,
    name: "Precision Tech",
    phone: "+40 725 666 777",
    email: "eng@prectech.ro",
    address: "Zona Industriala, Sibiu",
    contactPerson: { name: "Victor Ionescu", email: "v.ionescu@prectech.ro" },
    observations: [],
  },
  {
    id: 9,
    name: "Blue Wave Agency",
    phone: "+40 732 444 555",
    email: "ads@bluewave.ro",
    address: "Str. Constanta, Mamaia",
    contactPerson: { name: "Laura Dumitru", email: "laura@bluewave.ro" },
    observations: [],
  },
  {
    id: 10,
    name: "Green Energy Solutions",
    phone: "+40 766 888 999",
    email: "solar@greenenergy.ro",
    address: "Soseaua Pipera, Bucuresti",
    contactPerson: { name: "Radu Filipescu", email: "r.filipescu@greenenergy.ro" },
    observations: [],
  },
];